<?php

namespace AppBundle\Repository;

/**
 * TaskERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskERepository extends \Doctrine\ORM\EntityRepository
{
}
